remote_theme: cam-emmauscollege/just-the-docs

title: Informatica naslag
description: Vindt hier antwoorden op veelgestelde vragen
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://emmauscollege.github.io" # the base hostname & protocol for your site, e.g. http://example.com
